name: Generate Changelog on Merge

on:
  push:
    tags:
      - '*'

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    env:  # Here the env variable is added
      ENV_VARIABLE: 'Your Value'  # Edit with your variable and value

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: New release
#        run: something

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          body: ${{steps.github_release.outputs.changelog}}

#      - name: Create CHANGELOG.md
#        id: create_file
#        run: echo "${{steps.build_changelog.outputs.changelog}}" > CHANGELOG.md
#
#      - name: Commit and push changes
#        run: |
#          git add CHANGELOG.md
#          git config --global user.email "actions@github.com"
#          git config --global user.name "GitHub Action"
#          git commit -m "Automatically update changelog" -a || exit 0
#          git push